---

apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-appset
  namespace: default
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/diLLec/argocd-tests.git
      revision: HEAD
      directories:
      - path: apps/lab/frontend/*.yml
  template:
    metadata:
      name: '{{.path.basename}}'
      annotations: 
          argocd.argoproj.io/sync-wave: '{{ app.wave }}'
    spec:
      project: "default"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
  templatePatch: |
    spec:
      sources:
        {{- range $source := .app.sources }}
          - {{ $source | toYaml | nindent 10 }}
        {{- end }}